services:

  geth:
    image: ethereum/client-go:stable
    container_name: geth
    restart: always
    ports:
      - "8545:8545"
      - "6060:6060"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./jwt.hex:/opt/jwt.hex
      - ./eth_data:/root/.ethereum
    command: >
      --mainnet
      --db.engine "pebble"
      --state.scheme "path"
      --syncmode "full"
      --gcmode "full"
      --http
      --http.port 8545
      --http.addr 0.0.0.0
      --http.api "eth,net,web3"
      --http.corsdomain "*"
      --http.vhosts "*"
      --ws
      --ws.port 8545
      --ws.addr 0.0.0.0
      --ws.api "eth,net,web3"
      --ws.origins "*"
      --metrics
      --metrics.addr 0.0.0.0
      --metrics.port 6060
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.vhosts "*"
      --authrpc.jwtsecret "/opt/jwt.hex"
      --port 30303
      --discovery.port 30303
      --cache 8192
      --txlookuplimit 0

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: always
    ports:
      - "5052:5052"
      - "5054:5054"
      - "9000:9000"
    volumes:
      - ./jwt.hex:/opt/jwt.hex
      - ./lighthouse_data:/root/.lighthouse
    command: >
      lighthouse
      beacon_node
      --network "mainnet"
      --http
      --http-port 5052
      --http-address "0.0.0.0"
      --http-allow-origin "*"
      --port 9000
      --metrics
      --metrics-address "0.0.0.0"
      --metrics-allow-origin 5054
      --execution-endpoint "http://geth:8551"
      --execution-jwt "/opt/jwt.hex"
      --checkpoint-sync-url https://mainnet.checkpoint.sigp.io
      --prune-blobs false