services:

  geth:
    image: ethereum/client-go:stable
    container_name: geth
    restart: always
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ./jwt.hex:/jwt.hex
      - ./eth_data:/root/.ethereum
    command: >
      --mainnet
      --db.engine "pebble"
      --state.scheme "path"
      --syncmode "full"
      --gcmode "full"
      --http
      --http.port 8545
      --http.addr 0.0.0.0
      --http.api "eth,net,web3"
      --http.corsdomain "*"
      --http.vhosts "*"
      --ws
      --ws.port 8545
      --ws.addr 0.0.0.0
      --ws.api "eth,net,web3"
      --ws.origins "*"
      --authrpc.port 8551
      --authrpc.vhosts "*"
      --authrpc.jwtsecret "/jwt.hex"
      --port 30303
      --discovery.port 30303
      --cache 8192
      --txlookuplimit 0

  nimbus:
    image: statusim/nimbus-eth2:multiarch-v25.7.1
    container_name: nimbus
    restart: always
    user: root
    ports:
      - 5052:5052
      - 9000:9000
      - 9000:9000/udp
    volumes:
      - ./jwt.hex:/jwt.hex
      - ./nimbus_data:/home/user/nimbus-eth2/build/data
    command: >
      --network="mainnet"
      --data-dir="/home/user/nimbus-eth2/build/data"
      --tcp-port=9000
      --udp-port=9000
      --rest
      --rest-port=5052
      --rest-address="0.0.0.0"
      --rest-allow-origin="*"
      --web3-url="http://geth:8551"
      --jwt-secret="/jwt.hex"
      --enr-auto-update=true