services:

  geth:
    build: .
    container_name: geth
    restart: always
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ./data:/bnb/data
      - ./config.toml:/bnb/config.toml
    command: >
      geth
      --config /bnb/config.toml
      --datadir /bnb/data
      --cache 4096
      --http
      --http.vhosts *
      --http.port 8545
      --http.corsdomain *
      --http.api eth,net,web3,txpool,parlia
      --http.addr 0.0.0.0
      --ws
      --ws.addr 0.0.0.0
      --ws.api net,web3,eth
      --ws.origins *
      --ws.port 8545
      --rpc.allow-unprotected-txs
      --history.transactions 0
      --tries-verify-mode none
      --state.scheme path
      --gcmode full
      --syncmode full
      --txlookuplimit 0
      --verbosity 3